/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedexpensesExpensesImport } from './routes/_authenticated/(expenses)/expenses'
import { Route as AuthenticatedexpensesCreateImport } from './routes/_authenticated/(expenses)/create'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedexpensesExpensesRoute =
  AuthenticatedexpensesExpensesImport.update({
    id: '/(expenses)/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedexpensesCreateRoute =
  AuthenticatedexpensesCreateImport.update({
    id: '/(expenses)/create',
    path: '/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(expenses)/create': {
      id: '/_authenticated/(expenses)/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedexpensesCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(expenses)/expenses': {
      id: '/_authenticated/(expenses)/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedexpensesExpensesImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedexpensesCreateRoute: typeof AuthenticatedexpensesCreateRoute
  AuthenticatedexpensesExpensesRoute: typeof AuthenticatedexpensesExpensesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedexpensesCreateRoute: AuthenticatedexpensesCreateRoute,
  AuthenticatedexpensesExpensesRoute: AuthenticatedexpensesExpensesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/create': typeof AuthenticatedexpensesCreateRoute
  '/expenses': typeof AuthenticatedexpensesExpensesRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/create': typeof AuthenticatedexpensesCreateRoute
  '/expenses': typeof AuthenticatedexpensesExpensesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/(expenses)/create': typeof AuthenticatedexpensesCreateRoute
  '/_authenticated/(expenses)/expenses': typeof AuthenticatedexpensesExpensesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/profile' | '/' | '/create' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/profile' | '/' | '/create' | '/expenses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/(expenses)/create'
    | '/_authenticated/(expenses)/expenses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/about"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/",
        "/_authenticated/(expenses)/create",
        "/_authenticated/(expenses)/expenses"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(expenses)/create": {
      "filePath": "_authenticated/(expenses)/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(expenses)/expenses": {
      "filePath": "_authenticated/(expenses)/expenses.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
